### ISSUE TITLE
Devtools styling?

### ISSUE THREAD

**Issue by skbolton** [eduardhojbota/moonlight-userChrome#1]
Would you be interested in adding theming of the devtools? I have started work on a pr for it but I wanted to check in before I put in the work to finalize things. Here is a sample of what it will look like

Before:
<img width="1680" alt="before" src="https://user-images.githubusercontent.com/13260877/84556821-8f00c480-ace2-11ea-82ad-1b17c3193de1.png">

After:
<img width="1680" alt="after" src="https://user-images.githubusercontent.com/13260877/84556826-96c06900-ace2-11ea-9ccb-286ac6beefac.png">

**Comment by eduardhojbota** [comment]
Yes! That looks amazing! Please summit the PR.

**Comment by skbolton** [comment]
This weekend I got the dark theme taken care of. Next weekend I will post the PR. I am just tweaking the theme so that if users have the light dev tool theme enabled it will match the theme.

**Comment by eduardhojbota** [comment]
PR merged.
