### ISSUE TITLE
Extra space on the right side of menu with vanilla bars order + titlebar controls

### ISSUE THREAD

**Issue by GiganticThirstyHerald** [eduardhojbota/moonlight-userChrome#4]
![firefox_ts4VEGZLKs](https://user-images.githubusercontent.com/18756851/90596807-fe7ebd00-e219-11ea-84b4-71b1cbf5d064.png)
Also tabs are over title bar controls

**Comment by eduardhojbota** [comment]
Closing issue due to lack of details.
