### ISSUE TITLE
Container tab icons always rendered in blue

### ISSUE THREAD

**Issue by cubetastic33** [eduardhojbota/moonlight-userChrome#5]
![image](https://user-images.githubusercontent.com/33519300/107137089-03057200-692f-11eb-845a-95615fb69e66.png)

As you can see in the screenshot, the container name and the underline in the tab are shown with proper colors, but the icon is rendered in blue. It would make more sense if the icon was also yellow like the name and the underline.

**Comment by eduardhojbota** [comment]
The theme is strictly built for vanilla firefox.
